language: php
php:
- '5.6'
- '7.0'
- hhvm
env:
  - INTL_VERSION="2.3.*"
  - INTL_VERSION="3.0.*"
before_script:
- composer self-update
- composer require symfony/intl:${INTL_VERSION}
- composer install --prefer-source --no-interaction