language: php
php:
- '5.6'
- '7.0'
- '7.1'
env:
  - INTL_VERSION="2.3.*"
  - INTL_VERSION="3.0.*"
  - INTL_VERSION="4.0.*"
matrix:
  exclude:
  - php: '5.6'
    env: INTL_VERSION="4.0.*"
  - php: '7.0'
    env: INTL_VERSION="4.0.*"
before_script:
- composer self-update
- composer require symfony/intl:${INTL_VERSION}
- composer install --prefer-source --no-interaction
notifications:
  email:
    on_success: never
    on_failure: always
